export const ROLE_PERMISSION_CATALOG = {
  admin: [
    'admin',
    'ledger.read',
    'ledger.write',
    'ledger.audit',
    'proof.read',
    'proof.manage',
    'users.read',
    'users.manage',
    'roles.manage',
    'orders.read',
    'orders.write',
    'orders.status.write',
    'inventory.read',
    'inventory.write',
    'inventory.scan.write',
    'shipping.read',
    'shipping.write',
    'billing.read',
    'billing.write',
    'moderation.read',
    'moderation.write',
    'devices.read',
    'devices.manage',
    'device.events.write',
    'admin.override.write',
    'settings.read',
    'settings.write',
  ],
  operations_manager: [
    'ledger.read',
    'ledger.write',
    'ledger.audit',
    'proof.read',
    'proof.manage',
    'users.read',
    'orders.read',
    'orders.write',
    'orders.status.write',
    'inventory.read',
    'inventory.write',
    'inventory.scan.write',
    'shipping.read',
    'shipping.write',
    'billing.read',
    'moderation.read',
    'devices.read',
    'admin.override.write',
    'settings.read',
  ],
  inventory: [
    'ledger.read',
    'ledger.write',
    'proof.read',
    'orders.read',
    'inventory.read',
    'inventory.write',
    'inventory.scan.write',
    'shipping.read',
  ],
  shipping: [
    'ledger.read',
    'ledger.write',
    'proof.read',
    'orders.read',
    'orders.status.write',
    'inventory.read',
    'inventory.scan.write',
    'shipping.read',
    'shipping.write',
  ],
  billing: ['ledger.read', 'ledger.audit', 'proof.read', 'orders.read', 'inventory.read', 'shipping.read', 'billing.read', 'billing.write'],
  moderator: ['ledger.read', 'ledger.write', 'ledger.audit', 'proof.read', 'proof.manage', 'orders.read', 'inventory.read', 'shipping.read', 'moderation.read', 'moderation.write', 'devices.read'],
  auditor: [
    'ledger.read',
    'ledger.audit',
    'proof.read',
    'orders.read',
    'inventory.read',
    'shipping.read',
    'billing.read',
    'moderation.read',
    'devices.read',
    'settings.read',
  ],
  device_technician: ['ledger.read', 'ledger.write', 'devices.read', 'devices.manage', 'device.events.write'],
  support: ['ledger.read', 'proof.read', 'users.read', 'orders.read', 'inventory.read', 'shipping.read', 'moderation.read', 'devices.read', 'settings.read'],
  viewer: ['ledger.read', 'proof.read', 'orders.read', 'inventory.read', 'shipping.read'],
} as const;

export type RoleName = keyof typeof ROLE_PERMISSION_CATALOG;

export const ROLE_NAMES = Object.keys(ROLE_PERMISSION_CATALOG) as RoleName[];
