import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';
import { LedgerEventsService } from './ledger-events.service';

describe('LedgerEventsService', () => {
  let service: LedgerEventsService;
  let http: HttpTestingController;

  beforeEach(() => {
    localStorage.setItem('tnl.authToken', 'test-auth-token');

    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [LedgerEventsService],
    });

    service = TestBed.inject(LedgerEventsService);
    http = TestBed.inject(HttpTestingController);
  });

  afterEach(() => {
    localStorage.removeItem('tnl.authToken');
    http.verify();
  });

  it('should fetch an empty ledger event list', () => {
    let receivedEvents: unknown;
    let receivedError: unknown;

    service.fetchEvents().subscribe({
      next: (events) => {
        receivedEvents = events;
      },
      error: (error) => {
        receivedError = error;
      },
    });

    const request = http.expectOne('/api/v1/ledger/events');
    expect(request.request.method).toBe('GET');
    expect(request.request.headers.get('Authorization')).toContain('Bearer ');
    request.flush([]);

    expect(receivedError).toBeUndefined();
    expect(receivedEvents).toEqual([]);
  });

  it('should reject invalid ledger event responses', () => {
    let receivedEvents: unknown;
    let receivedError: unknown;

    service.fetchEvents().subscribe({
      next: (events) => {
        receivedEvents = events;
      },
      error: (error) => {
        receivedError = error;
      },
    });

    const request = http.expectOne('/api/v1/ledger/events');
    request.flush([{ invalid: true }]);

    expect(receivedEvents).toBeUndefined();
    expect(receivedError).toBeInstanceOf(Error);
  });

  it('should expose API authorization errors as user-facing errors', () => {
    let receivedEvents: unknown;
    let receivedError: unknown;

    service.fetchEvents().subscribe({
      next: (events) => {
        receivedEvents = events;
      },
      error: (error) => {
        receivedError = error;
      },
    });

    const request = http.expectOne('/api/v1/ledger/events');
    request.flush(
      {
        statusCode: 401,
        message: 'Unauthorized',
        error: 'Unauthorized',
      },
      {
        status: 401,
        statusText: 'Unauthorized',
      },
    );

    expect(receivedEvents).toBeUndefined();
    expect(receivedError).toEqual(new Error('Unauthorized'));
  });

  it('should create demo events with business data only', () => {
    let createdEvent: unknown;
    let receivedError: unknown;

    service.createDemoEvent().subscribe({
      next: (event) => {
        createdEvent = event;
      },
      error: (error) => {
        receivedError = error;
      },
    });

    const request = http.expectOne('/api/v1/ledger/events');
    expect(request.request.method).toBe('POST');
    expect(request.request.headers.get('Authorization')).toContain('Bearer ');
    expect(request.request.body).toEqual({
      type: 'LEDGER_EVENT',
      subjectType: 'ledger-session',
      subjectId: 'session-demo',
      payload: {
        action: 'demo-event',
        description: 'Generated by ledger-web demo flow',
      },
    });

    request.flush({
      id: '550e8400-e29b-41d4-a716-446655440000',
      type: 'LEDGER_EVENT',
      actorType: 'user',
      actorId: 'frontend-demo',
      subjectType: 'ledger-session',
      subjectId: 'session-demo',
      payload: request.request.body.payload,
      metadata: {
        tenantId: '00000000-0000-0000-0000-000000000000',
        requestId: 'request-1',
        correlationId: 'correlation-1',
        userAgent: 'test',
        payloadHash: 'a'.repeat(64),
        eventHash: 'b'.repeat(64),
        chainSequence: 1,
        result: 'accepted',
        timestamp: new Date().toISOString(),
      },
      createdAt: new Date().toISOString(),
    });

    expect(receivedError).toBeUndefined();
    expect(createdEvent).toMatchObject({
      type: 'LEDGER_EVENT',
      subjectId: 'session-demo',
    });
  });
});
