import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';
import type { LedgerEventResponse } from '@true-north-ledger/shared-models';
import { LedgerEventsService } from './ledger-events.service';

function buildEvent(id = '550e8400-e29b-41d4-a716-446655440000'): LedgerEventResponse {
  return {
    id,
    type: 'LEDGER_EVENT',
    actorType: 'user',
    actorId: 'frontend-demo',
    subjectType: 'ledger-session',
    subjectId: 'session-demo',
    payload: {
      action: 'demo-event',
      description: 'Generated by ledger-web demo flow',
    },
    metadata: {
      tenantId: '00000000-0000-0000-0000-000000000000',
      requestId: 'request-1',
      correlationId: 'correlation-1',
      userAgent: 'test',
      payloadHash: 'a'.repeat(64),
      eventHash: 'b'.repeat(64),
      chainSequence: 1,
      result: 'accepted',
      timestamp: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
  };
}

describe('LedgerEventsService', () => {
  let service: LedgerEventsService;
  let http: HttpTestingController;

  beforeEach(() => {
    localStorage.setItem('tnl.authToken', 'test-auth-token');

    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [LedgerEventsService],
    });

    service = TestBed.inject(LedgerEventsService);
    http = TestBed.inject(HttpTestingController);
  });

  afterEach(() => {
    localStorage.removeItem('tnl.authToken');
    http.verify();
  });

  it('should fetch an empty ledger event list', () => {
    let receivedEvents: unknown;
    let receivedError: unknown;

    service.fetchEvents().subscribe({
      next: (events) => {
        receivedEvents = events;
      },
      error: (error) => {
        receivedError = error;
      },
    });

    const request = http.expectOne('/api/v1/ledger/events');
    expect(request.request.method).toBe('GET');
    expect(request.request.headers.get('Authorization')).toContain('Bearer ');
    request.flush([]);

    expect(receivedError).toBeUndefined();
    expect(receivedEvents).toEqual([]);
  });

  it('should reject invalid ledger event responses', () => {
    let receivedEvents: unknown;
    let receivedError: unknown;

    service.fetchEvents().subscribe({
      next: (events) => {
        receivedEvents = events;
      },
      error: (error) => {
        receivedError = error;
      },
    });

    const request = http.expectOne('/api/v1/ledger/events');
    request.flush([{ invalid: true }]);

    expect(receivedEvents).toBeUndefined();
    expect(receivedError).toBeInstanceOf(Error);
  });

  it('should expose API authorization errors as user-facing errors', () => {
    let receivedEvents: unknown;
    let receivedError: unknown;

    service.fetchEvents().subscribe({
      next: (events) => {
        receivedEvents = events;
      },
      error: (error) => {
        receivedError = error;
      },
    });

    const request = http.expectOne('/api/v1/ledger/events');
    request.flush(
      {
        statusCode: 401,
        message: 'Unauthorized',
        error: 'Unauthorized',
      },
      {
        status: 401,
        statusText: 'Unauthorized',
      },
    );

    expect(receivedEvents).toBeUndefined();
    expect(receivedError).toEqual(new Error('Unauthorized'));
  });

  it('should create demo events with business data only', () => {
    let createdEvent: unknown;
    let receivedError: unknown;

    service.createDemoEvent().subscribe({
      next: (event) => {
        createdEvent = event;
      },
      error: (error) => {
        receivedError = error;
      },
    });

    const request = http.expectOne('/api/v1/ledger/events');
    expect(request.request.method).toBe('POST');
    expect(request.request.headers.get('Authorization')).toContain('Bearer ');
    expect(request.request.body).toEqual({
      type: 'LEDGER_EVENT',
      subjectType: 'ledger-session',
      subjectId: 'session-demo',
      payload: {
        action: 'demo-event',
        description: 'Generated by ledger-web demo flow',
      },
    });

    request.flush(buildEvent());

    expect(receivedError).toBeUndefined();
    expect(createdEvent).toMatchObject({
      type: 'LEDGER_EVENT',
      subjectId: 'session-demo',
    });
  });

  it('should fetch a single ledger event by id', () => {
    let receivedEvent: unknown;
    let receivedError: unknown;

    service.fetchEvent('550e8400-e29b-41d4-a716-446655440000').subscribe({
      next: (event) => {
        receivedEvent = event;
      },
      error: (error) => {
        receivedError = error;
      },
    });

    const request = http.expectOne('/api/v1/ledger/events/550e8400-e29b-41d4-a716-446655440000');
    expect(request.request.method).toBe('GET');
    expect(request.request.headers.get('Authorization')).toContain('Bearer ');
    request.flush(buildEvent());

    expect(receivedError).toBeUndefined();
    expect(receivedEvent).toMatchObject({ id: '550e8400-e29b-41d4-a716-446655440000' });
  });

  it('should reject invalid single event responses', () => {
    let receivedEvent: unknown;
    let receivedError: unknown;

    service.fetchEvent('bad-event').subscribe({
      next: (event) => {
        receivedEvent = event;
      },
      error: (error) => {
        receivedError = error;
      },
    });

    const request = http.expectOne('/api/v1/ledger/events/bad-event');
    request.flush({ invalid: true });

    expect(receivedEvent).toBeUndefined();
    expect(receivedError).toBeInstanceOf(Error);
  });

  it('should expose HTTP status details when the API does not return a message', () => {
    let receivedError: unknown;

    service.createDemoEvent().subscribe({
      error: (error) => {
        receivedError = error;
      },
    });

    const request = http.expectOne('/api/v1/ledger/events');
    request.flush({}, { status: 503, statusText: 'Service Unavailable' });

    expect(receivedError).toEqual(new Error('Failed to create ledger event: 503 Service Unavailable'));
  });

  it('should reject invalid create responses', () => {
    let receivedEvent: unknown;
    let receivedError: unknown;

    service.createDemoEvent().subscribe({
      next: (event) => {
        receivedEvent = event;
      },
      error: (error) => {
        receivedError = error;
      },
    });

    const request = http.expectOne('/api/v1/ledger/events');
    request.flush({ invalid: true });

    expect(receivedEvent).toBeUndefined();
    expect(receivedError).toBeInstanceOf(Error);
  });
});
