import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import {
  AppendLedgerEventDtoSchema,
  LedgerEventResponse,
  LedgerEventResponseSchema,
} from '@true-north-ledger/shared-models';

@Injectable({
  providedIn: 'root',
})
export class LedgerEventsService {
  private readonly http = inject(HttpClient);

  fetchEvents(): Observable<LedgerEventResponse[]> {
    return this.http.get<unknown>('/api/v1/ledger/events', this.authOptions()).pipe(
      map((raw) => {
        const parsed = LedgerEventResponseSchema.array().safeParse(raw);
        if (!parsed.success) {
          throw new Error(`Ledger events response is invalid: ${JSON.stringify(parsed.error.format())}`);
        }
        return parsed.data;
      }),
      catchError((error) => {
        console.error('Failed to fetch events', error);
        return throwError(() => this.toUserFacingError(error, 'Failed to fetch ledger events'));
      }),
    );
  }

  createDemoEvent(): Observable<LedgerEventResponse> {
    const payload = {
      action: 'demo-event',
      description: 'Generated by ledger-web demo flow',
    };

    const dto = {
      type: 'LEDGER_EVENT' as const,
      subjectType: 'ledger-session',
      subjectId: 'session-demo',
      payload,
    };

    const validated = AppendLedgerEventDtoSchema.parse(dto);
    return this.http.post<unknown>('/api/v1/ledger/events', validated, this.authOptions()).pipe(
      map((raw) => {
        const parsed = LedgerEventResponseSchema.safeParse(raw);
        if (!parsed.success) {
          throw new Error(`Invalid ledger event created by API: ${JSON.stringify(parsed.error.format())}`);
        }
        return parsed.data;
      }),
      catchError((error) => {
        console.error('Failed to create demo event', error);
        return throwError(() => this.toUserFacingError(error, 'Failed to create ledger event'));
      }),
    );
  }

  fetchEvent(id: string): Observable<LedgerEventResponse> {
    return this.http.get<unknown>(`/api/v1/ledger/events/${id}`, this.authOptions()).pipe(
      map((raw) => {
        const parsed = LedgerEventResponseSchema.safeParse(raw);
        if (!parsed.success) {
          throw new Error(`Ledger event response is invalid: ${JSON.stringify(parsed.error.format())}`);
        }
        return parsed.data;
      }),
      catchError((error) => {
        console.error(`Failed to fetch event ${id}`, error);
        return throwError(() => this.toUserFacingError(error, `Failed to fetch ledger event ${id}`));
      }),
    );
  }

  private toUserFacingError(error: unknown, fallbackMessage: string): Error {
    if (error instanceof HttpErrorResponse) {
      const apiMessage =
        typeof error.error === 'object' && error.error && 'message' in error.error
          ? String((error.error as { message: unknown }).message)
          : undefined;
      const statusMessage = error.status ? `${error.status} ${error.statusText}`.trim() : 'network error';
      return new Error(apiMessage ?? `${fallbackMessage}: ${statusMessage}`);
    }

    return error instanceof Error ? error : new Error(fallbackMessage);
  }

  private authOptions(): { headers?: { Authorization: string } } {
    const token = localStorage.getItem('tnl.authToken');
    return token
      ? {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      : {};
  }
}
