import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, throwError, from } from 'rxjs';
import { map, catchError, switchMap } from 'rxjs/operators';
import {
  AppendLedgerEventDtoSchema,
  LedgerEventResponse,
  LedgerEventResponseSchema,
} from '@true-north-ledger/shared-models';

@Injectable({
  providedIn: 'root',
})
export class LedgerEventsService {
  constructor(private readonly http: HttpClient) {}

  fetchEvents(): Observable<LedgerEventResponse[]> {
    return this.http.get<unknown>('/api/v1/ledger/events').pipe(
      map((raw) => {
        const parsed = LedgerEventResponseSchema.array().safeParse(raw);
        if (!parsed.success) {
          throw new Error(`Ledger events response is invalid: ${JSON.stringify(parsed.error.format())}`);
        }
        return parsed.data;
      }),
      catchError((error) => {
        console.error('Failed to fetch events', error);
        return throwError(() => error);
      }),
    );
  }

  createDemoEvent(): Observable<LedgerEventResponse> {
    const payload = {
      action: 'demo-event',
      description: 'Generated by ledger-web demo flow',
    };
    const metadata = {
      tenantId: '00000000-0000-0000-0000-000000000000',
      requestId: crypto.randomUUID(),
      correlationId: undefined,
      sourceIp: undefined,
      userAgent: navigator.userAgent,
      payloadHash: '', // will be computed
      previousHash: undefined,
      result: 'accepted' as const,
      timestamp: new Date().toISOString(),
    };

    return from(this.computePayloadHash(payload)).pipe(
      switchMap((payloadHash) => {
        const dto = {
          type: 'LEDGER_EVENT' as const,
          actorType: 'user' as const,
          actorId: 'frontend-demo',
          subjectType: 'ledger-session',
          subjectId: 'session-demo',
          payload,
          metadata: { ...metadata, payloadHash },
        };

        const validated = AppendLedgerEventDtoSchema.parse(dto);
        return this.http.post<unknown>('/api/v1/ledger/events', validated);
      }),
      map((raw) => {
        const parsed = LedgerEventResponseSchema.safeParse(raw);
        if (!parsed.success) {
          throw new Error(`Invalid ledger event created by API: ${JSON.stringify(parsed.error.format())}`);
        }
        return parsed.data;
      }),
      catchError((error) => {
        console.error('Failed to create demo event', error);
        return throwError(() => error);
      }),
    );
  }

  fetchEvent(id: string): Observable<LedgerEventResponse> {
    return this.http.get<unknown>(`/api/v1/ledger/events/${id}`).pipe(
      map((raw) => {
        const parsed = LedgerEventResponseSchema.safeParse(raw);
        if (!parsed.success) {
          throw new Error(`Ledger event response is invalid: ${JSON.stringify(parsed.error.format())}`);
        }
        return parsed.data;
      }),
      catchError((error) => {
        console.error(`Failed to fetch event ${id}`, error);
        return throwError(() => error);
      }),
    );
  }

  private async computePayloadHash(payload: unknown): Promise<string> {
    const encoder = new TextEncoder();
    const data = encoder.encode(JSON.stringify(payload));
    const digest = await crypto.subtle.digest('SHA-256', data);
    return Array.from(new Uint8Array(digest))
      .map((byte) => byte.toString(16).padStart(2, '0'))
      .join('');
  }
}
