FROM node:22-alpine AS builder

WORKDIR /workspace

RUN corepack enable

COPY package.json pnpm-lock.yaml nx.json tsconfig.base.json ./
COPY apps ./apps
COPY libs ./libs

RUN pnpm install --frozen-lockfile
RUN pnpm nx run ledger-web:build:production

FROM nginx:1.27-alpine AS runner

COPY apps/docker/nginx/web.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /workspace/dist/apps/ledger-web/browser /usr/share/nginx/html

EXPOSE 80
